### ISSUE TITLE
.pbo file

### ISSUE THREAD

**Issue by TheUltimax** [Armitxes/TakistanLife#1]
Am I missing something or isn't there supposed to be a .pbo file somewhere?

**Comment by Armitxes** [comment]
Hello Ultimax,

first I must apologize for responding so late. As described in the readme, you should use the forums for such requests ^^ I'm currently restructuring the setup so that you don't need to setup a database manually, tomorrow there will be a new release with tutorial.

I recommend you setting up an account at armitxes.net (only you, as the server owner, need to do this)
Registration: https://armitxes.net/Account/Register/

You will love it :) so please have one more day of patience and the actual setup of the server will take you about 5 minutes.

**Comment by Armitxes** [comment]
Updated sources. Mission Sources (.pbo), Server Sources (@ArmiNET), and tutorial available on our website.
https://armitxes.net/Projects/TakistanLife/

Preview server will go online soon so you can take a look on the mission.
